[tools]
node = "latest"
python = "3.14"
ruby = "latest"
uv = "latest"
flutter = "latest"
rust = {
	version = "latest",
	profile = "default",
	components = "rust-analyzer",
}
lua = "5.1"
opencode = "latest"
claude = "latest"
rtk = "latest"
gh = "latest"
codex = "latest"
"pipx:graphifyy" = "latest"
worktrunk = "latest"
"npm:@nestjs/cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = [
	"node",
	"python",
]

[settings.python]
uv_venv_auto = true

[settings.ruby]
compile = false
