general {
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 900
    on-timeout = [ -f "$HOME/.local/state/omarchy/indicators/stay-awake" ] || systemctl suspend
}
